export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'

export const USER_FEATURED_REQUEST = 'USER_FEATURED_REQUEST'
export const USER_FEATURED_SUCCESS = 'USER_FEATURED_SUCCESS'
export const USER_FEATURED_FAIL = 'USER_FEATURED_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

